name: digit_classification
description: An end-to-end sample of a digit classification.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: 0.10.3
  image: 4.0.17
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/
 